#!/usr/bin/env lua

local repo = {}
local getopt = require("posix.unistd").getopt
local json = require("cjson")

local ENV="test"

local fconf = "/home/roach/.config/tman/pgns/repo.json"
local config = nil

local function read_file(fname)
    local res
    local f = io.open(fname)

    if not f then
        return "{}"
    end

    res = f:read("*a")
    f:close()
    return res ~= "" and res or "{}"
end

config = json.decode(read_file(fconf))[ENV] or {}


for i = 1, #arg do
    print(arg[i])
end

for optopt, optarg, optind in getopt(arg, "a") do

end


function repo.sync()
end

function repo.rsync()
end

function repo.cat()
end

function repo.help()
end

