#!/bin/bash

# Dumb wrapper so a plugin can call its libraries

PGNAME="tman-gun"
COMMAND=
TASKDIR=
PRJNAME=
TASKNAME=

OPTS=$(getopt -o i:p:T:h --long prj:,taskid:,taskdir:help -n "$PGNAME" -- "$@")
if [ $? -ne 0 ]; then
    #echo "error parsing options" >&2
    exit 1
fi

## Reset the positional parameters to the parsed options
eval set -- "$OPTS"

while true; do
    case "$1" in
        -i)
            TASKNAME="$2"
            shift 2
            ;;
        -p)
            PRJNAME="$2"
            shift 2
            ;;
        -T)
            TASKDIR="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "$PGNAME: invalid option '$1'" >&2
            exit 1
    esac
done

COMMAND="$1"

if [ -z "$COMMAND" ]; then
    echo "$PGNAME: no command passed"
    exit 1
fi

CWD="$(pwd)"
PGNDIR="`dirname $0`"

cd "$PGNDIR" || exit 1
lua gun.lua -p "$PRJNAME" -T "$TASKDIR" -i "$TASKNAME" "$COMMAND"
res="$?"
cd "$CWD" || exit 1
exit "$res"
