#!/bin/bash

# Dumb wrapper so a plugin can call its libraries

PGNAME="gun"
COMMAND=
TASKDIR=
PRJNAME=
TASKNAME=

OPTS=$(getopt -o i:p:T:h --long prj:,taskid:,taskdir:help -n "$PGNAME" -- "$@")
if [ $? -ne 0 ]; then
    #echo "error parsing options" >&2
    exit 1
fi

## Reset the positional parameters to the parsed options
eval set -- "$OPTS"

while true; do
    case "$1" in
        -i)
            TASKNAME="$2"
            shift 2
            ;;
        -p)
            PRJNAME="$2"
            shift 2
            ;;
        -T)
            TASKDIR="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "$PGNAME: invalid option '$1'" >&2
            exit 1
    esac
done

COMMAND="$1"

if [ -z "$COMMAND" ]; then
    echo "$PGNAME: no command passed"
    exit 1
fi



function time_init()
{
    return 0;
}

function time_sync()
{
    echo "time_sync: under development"
    return 0;
}

function time_rsync()
{
    echo "time_rsync: under development"
    return 0;
}

function time_show()
{
    echo "otime  : original time expectation"
    echo "stime  : time spent on task"
    return 0;
}

function time_help()
{
    echo "Usage: repo [sync|rsync|show|help]"
}


if [ -z "$COMMAND" -o "$COMMAND" = "sync" ]; then
    time_sync
elif [ "$COMMAND" = "rsync" ]; then
    time_rsync
elif [ "$COMMAND" = "show" ]; then
    time_show
elif [ "$COMMAND" = "help" ]; then
    time_help
else
    echo "$PGNAME: no such command '$COMMAND'" && exit 1
fi
