#!/bin/bash

PGNAME="find"
PATTERN=
TASKDIR=
PRJNAME=
TASKNAME=

function usage()
{
    cat << EOF
Usage: tman find [OPTION]... PATTERN
    Find items in database.

    Options:
      -i    find task ID by PATTERN (under development)
      -b    find board name by PATTERN  (under development)
      -p    find project name by PATTERN (under development)
EOF
}


OPTS=$(getopt -o i:p:T:h --long prj:,taskid:,taskdir:help -n "$PGNAME" -- "$@")
if [ $? -ne 0 ]; then
    #echo "error parsing options" >&2
    exit 1
fi

## Reset the positional parameters to the parsed options
eval set -- "$OPTS"

while true; do
    case "$1" in
        -i)
            TASKNAME="$2"
            shift 2
            ;;
        -p)
            PRJNAME="$2"
            shift 2
            ;;
        -T)
            TASKDIR="$2"
            shift 2
            ;;
        -h)
            usage
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "$PGNAME: invalid option '$1'" >&2
            exit 1
    esac
done

PATTERN="$1"
if [ -z "$PATTERN" ]; then
    echo "${PGNAME}: no pattern passed" >&2
    exit 1
fi

for prj in $(ls "$TASKDIR"); do
    find "$TASKDIR/$prj" -maxdepth 1 -name "*${PATTERN}*" | while read -r res; do
        res="${res/$TASKDIR\//}"
        PRJ="$(echo "$res" | cut -f 1 -d '/')"
        ID="$(echo "$res" | cut -f 2 -d '/')"
        echo "$PRJ - $ID"
    done
done
